// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package helloworld.rpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\")\n\014HelloRequest\022\014\n\004name\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\"*\n\nHelloReply\022\017\n\007messa" +
      "ge\030\001 \001(\t\022\013\n\003age\030\002 \001(\0052\313\001\n\007Greeter\022(\n\010Say" +
      "Hello\022\r.HelloRequest\032\013.HelloReply\"\000\022-\n\013M" +
      "ultiReplay\022\r.HelloRequest\032\013.HelloReply\"\000" +
      "0\001\022,\n\nMultiHello\022\r.HelloRequest\032\013.HelloR" +
      "eply\"\000(\001\0229\n\025MultiHelloMultiReplay\022\r.Hell" +
      "oRequest\032\013.HelloReply\"\000(\0010\00122\n\005TestG\022)\n\t" +
      "TestHello\022\r.HelloRequest\032\013.HelloReply\"\000B" +
      "#\n\016helloworld.rpcB\017HelloWorldProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new java.lang.String[] { "Message", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
