// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package helloworld.rpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
